from crear_excel_inicial import crear_excel_inicial
from automatizacion_inventario import automatizacion_inventario
from automatizacion_avanzada import automatizacion_avanzada

crear_excel_inicial()
automatizacion_inventario()
automatizacion_avanzada()